apiVersion: v1
kind: Service
metadata:
  name: pigeonbox-frontend
  namespace: pigeonbox
  labels:
    app: pigeonbox
    component: frontend
spec:
  selector:
    app: pigeonbox
    component: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
